name: Query Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'query/**' # Adjust the path to match your directory structure
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'query/**' # Adjust the path to match your directory structure

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Navigate to query directory
        run: cd query

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test

  sonar_analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_and_push_docker:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: sonar_analysis

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yashvanth24/micro-services:query-latest
